### ISSUE TITLE
Electron rebuild fails at compiling serialport

### ISSUE THREAD

**Issue by eMarek** [serialport/node-serialport#1993]
### Summary of Problem

I am trying to rebuild serialport with electron-rebuild, but it fails with bunch of errors:
```
my-computer:my-app my-username$ electron-rebuild
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.1
gyp info using node@12.13.1 | darwin | x64
gyp info find Python using Python version 3.7.4 found at "/usr/local/opt/python/bin/python3.7"
gyp info spawn /usr/local/opt/python/bin/python3.7
gyp info spawn args [
gyp info spawn args   '/Users/my-username/Documents/bdi/my-app/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/my-username/Documents/bdi/my-app/node_modules/firmata/node_modules/@serialport/bindings/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/my-username/Documents/bdi/my-app/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/my-username/.electron-gyp/7.1.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/my-username/.electron-gyp/7.1.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/my-username/Documents/bdi/my-app/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/my-username/.electron-gyp/7.1.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/my-username/Documents/bdi/my-app/node_modules/firmata/node_modules/@serialport/bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/bindings/src/serialport.o
../src/serialport.cpp:329:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("cts").ToLocalChecked(), Nan::New<v8::Boolean>(data->cts));
    ~~~~~~~~~^~~
/Users/my-username/.electron-gyp/7.1.1/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/my-username/.electron-gyp/7.1.1/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:330:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("dsr").ToLocalChecked(), Nan::New<v8::Boolean>(data->dsr));
    ~~~~~~~~~^~~
/Users/my-username/.electron-gyp/7.1.1/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/my-username/.electron-gyp/7.1.1/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:331:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("dcd").ToLocalChecked(), Nan::New<v8::Boolean>(data->dcd));
    ~~~~~~~~~^~~
/Users/my-username/.electron-gyp/7.1.1/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/my-username/.electron-gyp/7.1.1/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:378:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("baudRate").ToLocalChecked(), Nan::New<v8::Integer>(data->baudRate));
    ~~~~~~~~~^~~
/Users/my-username/.electron-gyp/7.1.1/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/my-username/.electron-gyp/7.1.1/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
4 errors generated.
make: *** [Release/obj.target/bindings/src/serialport.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/my-username/Documents/bdi/my-app/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/Users/my-username/Documents/bdi/my-app/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=7.1.1" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/my-username/Documents/bdi/my-app/node_modules/firmata/node_modules/@serialport/bindings
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.1
gyp info using node@12.13.1 | darwin | x64
gyp info find Python using Python version 3.7.4 found at "/usr/local/opt/python/bin/python3.7"
gyp info spawn /usr/local/opt/python/bin/python3.7
gyp info spawn args [
gyp info spawn args   '/Users/my-username/Documents/bdi/my-app/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/my-username/Documents/bdi/my-app/node_modules/firmata/node_modules/@serialport/bindings/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/my-username/Documents/bdi/my-app/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/my-username/.electron-gyp/7.1.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/my-username/.electron-gyp/7.1.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/my-username/Documents/bdi/my-app/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/my-username/.electron-gyp/7.1.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/my-username/Documents/bdi/my-app/node_modules/firmata/node_modules/@serialport/bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/bindings/src/serialport.o
../src/serialport.cpp:329:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("cts").ToLocalChecked(), Nan::New<v8::Boolean>(data->cts));
    ~~~~~~~~~^~~
/Users/my-username/.electron-gyp/7.1.1/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/my-username/.electron-gyp/7.1.1/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:330:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("dsr").ToLocalChecked(), Nan::New<v8::Boolean>(data->dsr));
    ~~~~~~~~~^~~
/Users/my-username/.electron-gyp/7.1.1/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/my-username/.electron-gyp/7.1.1/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:331:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("dcd").ToLocalChecked(), Nan::New<v8::Boolean>(data->dcd));
    ~~~~~~~~~^~~
/Users/my-username/.electron-gyp/7.1.1/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/my-username/.electron-gyp/7.1.1/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/serialport.cpp:378:14: error: no matching member function for call to 'Set'
    results->Set(Nan::New<v8::String>("baudRate").ToLocalChecked(), Nan::New<v8::Integer>(data->baudRate));
    ~~~~~~~~~^~~
/Users/my-username/.electron-gyp/7.1.1/include/node/v8.h:3455:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/my-username/.electron-gyp/7.1.1/include/node/v8.h:3458:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
4 errors generated.
make: *** [Release/obj.target/bindings/src/serialport.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/my-username/Documents/bdi/my-app/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/Users/my-username/Documents/bdi/my-app/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=7.1.1" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/my-username/Documents/bdi/my-app/node_modules/firmata/node_modules/@serialport/bindings
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/Users/my-username/Documents/bdi/my-app/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/Users/my-username/Documents/bdi/my-app/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/Users/my-username/Documents/bdi/my-app/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/Users/my-username/Documents/bdi/my-app/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/Users/my-username/Documents/bdi/my-app/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/Users/my-username/Documents/bdi/my-app/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/Users/my-username/Documents/bdi/my-app/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/Users/my-username/Documents/bdi/my-app/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/Users/my-username/Documents/bdi/my-app/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/my-username/Documents/bdi/my-app/node_modules/rxjs/internal/Subscriber.js:143:22)
```

This shouldn't end like this, but with a success I guess.

### Code to Reproduce the Issue
 My package.json file:
```js
{
  "main": "main/index.js",
  "scripts": {
    "start:app": "cross-env NODE_ENV=development electron .",
    "postinstall": "electron-rebuild"
  },
  "devDependencies": {
    "cross-env": "^6.0.3",
    "electron": "^7.1.1",
    "electron-rebuild": "^1.8.8",
    "node-gyp": "^6.0.1"
  },
  "dependencies": {
    "johnny-five": "^1.3.1",
    "serialport": "^8.0.5"
  }
}
```

### Versions, Operating System and Hardware

- SerialPort@8.0.5
- Node.js v12.13.1
- npm 6.12.1
- node-gyp v6.0.1
- yarn 1.19.1
- macOS Catalina Version 10.15.1
- Python 2.7.16

I already opened same issue at [electron-rebuild](https://github.com/electron/electron-rebuild/issues/320), but they directed me here. I am a bit lost now.

**Comment by Raylin51** [comment]
Do you fix this problem? I would like to know how to fix it. Thanks!

**Comment by eMarek** [comment]
In my case problem was in outdated `serialport` inside `johnny-five` package. It was fixed by updating related packages. Take a look at https://github.com/electron/electron-rebuild/issues/320 and https://github.com/rwaldron/johnny-five/issues/1643.

**Comment by Raylin51** [comment]
Got it. Thanks!
