### ISSUE TITLE
Suddenly getting error when requiring serialport on Windows

### ISSUE THREAD

**Issue by AlCalzone** [serialport/node-serialport#2007]
### Summary of Problem

(Please answer all 3)

- What are you trying to do?
`require("serialport")`
- What happens?
```
Error: ENOENT: no such file or directory, access 'C:\Repositories\node-zwave-js\node_modules\@serialport\bindings\lib\package.json'
    at Object.accessSync (fs.js:205:3)
    at exists (C:\Repositories\node-zwave-js\node_modules\bindings\bindings.js:14:14)
    at Function.getRoot (C:\Repositories\node-zwave-js\node_modules\bindings\bindings.js:203:7)
    at bindings (C:\Repositories\node-zwave-js\node_modules\bindings\bindings.js:82:32)
    at Object.<anonymous> (C:\Repositories\node-zwave-js\node_modules\@serialport\bindings\lib\win32.js:1:36)
```
- What should have happened?
it should not throw

### Code to Reproduce the Issue

```js
require("serialport")
```

Not sure what changed, it used to work yesterday...

### Versions, Operating System and Hardware

- SerialPort@8.0.6
- Node.js v12.1.0
- Windows
- Hardware and chipset? unrelated

**Comment by AlCalzone** [comment]
Nevermind, the debugger just happened to stop here when I was debugging another issue.
