### ISSUE TITLE
Fail to get data from serialport while app is run with pm2

### ISSUE THREAD

**Issue by Jean-PhilippeD** [serialport/node-serialport#2014]
### Summary of Problem

Hello,

Here is my problem.
I'm trying to parse data from a usb enocean receiver with enocean-js lib, which uses node-serialport

Everything is working fine when I run my app with node app.js
But when I start my app through pm2 (pm2 start app.js), I can not get any data from my usb  device

### Code to Reproduce the Issue

```js
const port = new SerialPort('/dev/ttyUSB0', { baudRate: 57600 })

port.pipe(my.parser).pipe(my.transformer)

port.on('open', function() {
        console.log('Enocean :: Connected to enocean device')
 })

my.parser.on('data', data => {
        // Never came here with PM2
        console.log('some data arrived and has been parsed')
})

my.transformer.on('data', data => {
        // Never come here with PM2
        console.log('some data arrived and has been transformed')
})
```

I put serialport in debug and here is what I see when data received:

```
  serialport/bindings/poller received "readable" +9s
  serialport/bindings/unixRead Starting read +9s
  serialport/bindings/unixRead Finished read 5 bytes +0ms
  serialport/stream binding.read finished { bytesRead: 5 } +9s
```

And here is when it does not work through pm2

```
0|app   | 2020-01-14T21:23:02.954Z serialport/bindings/poller received "readable"
0|app   | 2020-01-14T21:23:02.956Z serialport/bindings/unixRead Starting read
0|app   | 2020-01-14T21:23:02.962Z serialport/bindings/unixRead Finished read undefined bytes
0|app   | 2020-01-14T21:23:02.963Z serialport/stream binding.read finished { bytesRead: undefined }
0|app   | 2020-01-14T21:23:02.964Z serialport/stream _read reading { start: NaN, toRead: NaN }
0|app   | 2020-01-14T21:23:02.965Z serialport/stream binding.read error TypeError: "offset" is not an integer got "NaN"
0|app   |     at LinuxBinding.read (/usr/lib/node_modules/app/node_modules/@serialport/binding-abstract/lib/index.js:89:13)
0|app   |     at LinuxBinding.read (/usr/lib/node_modules/app/node_modules/@serialport/bindings/lib/linux.js:63:17)
0|app   |     at SerialPort._read (/usr/lib/node_modules/app/node_modules/@serialport/stream/lib/index.js:375:16)
0|app   |     at SerialPort.Readable.read (_stream_readable.js:471:10)
0|app   |     at maybeReadMore_ (_stream_readable.js:615:12)
0|app   |     at process._tickCallback (internal/process/next_tick.js:63:19)
0|app   | 2020-01-14T21:23:02.966Z serialport/stream disconnected TypeError: "offset" is not an integer got "NaN"
0|app   |     at LinuxBinding.read (/usr/lib/node_modules/app/node_modules/@serialport/binding-abstract/lib/index.js:89:13)
0|app   |     at LinuxBinding.read (/usr/lib/node_modules/app/node_modules/@serialport/bindings/lib/linux.js:63:17)
0|app   |     at SerialPort._read (/usr/lib/node_modules/app/node_modules/@serialport/stream/lib/index.js:375:16)
0|app   |     at SerialPort.Readable.read (_stream_readable.js:471:10)
0|app   |     at maybeReadMore_ (_stream_readable.js:615:12)
0|app   |     at process._tickCallback (internal/process/next_tick.js:63:19)
0|app   | 2020-01-14T21:23:02.967Z serialport/stream #close
0|app   | 2020-01-14T21:23:02.967Z serialport/binding-abstract close
0|app   | 2020-01-14T21:23:02.967Z serialport/stream _read queueing _read for after open
0|app   | 2020-01-14T21:23:02.968Z serialport/bindings/poller Stopping poller
0|app   | 2020-01-14T21:23:02.968Z serialport/bindings/poller Destroying poller
0|app   | 2020-01-14T21:23:02.978Z serialport/stream binding.close finished
```

### Versions, Operating System and Hardware

- SerialPort@8.0.6
- Node.js v10.18.1
- Ubuntu
- PM2 2.4.0

**Comment by Jean-PhilippeD** [comment]
Solved.

PM2 was out of date.
I had 2.4 and I though it was up to date but it was not. 
I read 2.4 for the last version while it's 4.2 ... :)

With the last verion, the problem is solved !
