### ISSUE TITLE
Installing issue on Freebsd 11.2-STABLE

### ISSUE THREAD

**Issue by wubaodong** [serialport/node-serialport#2085]
install failed on Freebsd 11.2-STABLE

when run command  'npm install serialport --unsafe-perm --build-from-source', I got this logs:

 @serialport/bindings@9.0.0 install /root/serial-system-comm/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

gmake: Entering directory '/root/serial-system-comm/node_modules/@serialport/bindings/build'
  CXX(target) Release/obj.target/bindings/src/serialport.o
gmake: c++: No such file or directory
gmake: *** [bindings.target.mk:113: Release/obj.target/bindings/src/serialport.o] Error 127
gmake: Leaving directory '/root/serial-system-comm/node_modules/@serialport/bindings/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System FreeBSD 11.2-STABLE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/serial-system-comm/node_modules/@serialport/bindings
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN serial-system-comm@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@9.0.0 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @serialport/bindings@9.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-21T02_42_08_313Z-debug.log

Many thanks in advance!

**Comment by wubaodong** [comment]
my fault: I installed on FreeNAS which no build enviroment.
Close this issue.
