### ISSUE TITLE
Unresolved External Symbols with Node 12

### ISSUE THREAD

**Issue by KernelErr** [serialport/node-serialport#2098]
### Summary of Problem

When I try to run `eletron-rebuild`, I got unresolved external symbols error.

```
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.16.3 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\Li\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2019 (16.5.30104.148) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\Li\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'D:\\Dev\\electron-quick-start\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Dev\\electron-quick-start\\node_modules\\@serialport\\bindings\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Dev\\electron-quick-start\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Li\\.electron-gyp\\9.0.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Li\\.electron-gyp\\9.0.3',
gyp info spawn args   '-Dnode_gyp_dir=D:\\Dev\\electron-quick-start\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Li\\\\.electron-gyp\\\\9.0.3\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Dev\\electron-quick-start\\node_modules\\@serialport\\bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Dev\\electron-quick-start\\node_modules\\@serialport\\bindings\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
  serialport.cpp
  serialport_win.cpp
  win_delay_load_hook.cc
C:\Users\Li\.electron-gyp\9.0.3\include\node\v8.h(9116,39): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version. (编译源文件 ..\src\serialport_win.cpp) [D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\bindings.vcxproj]
C:\Users\Li\.electron-gyp\9.0.3\include\node\v8.h(9124,42): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version. (编译源文件 ..\src\serialport_win.cpp) [D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\bindings.vcxproj]
C:\Users\Li\.electron-gyp\9.0.3\include\node\v8.h(9116,39): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version. (编译源文件 ..\src\serialport.cpp) [D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\bindings.vcxproj]
C:\Users\Li\.electron-gyp\9.0.3\include\node\v8.h(9124,42): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version. (编译源文件 ..\src\serialport.cpp) [D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\bindings.vcxproj]
    正在创建库 D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\Release\bindings.lib 和对象 D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\Release\bindings.exp
serialport.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: static class v8::Local<class v8::FunctionTemplate> __cdecl v8::FunctionTemplate::New(class v8::Isolate *,void (__cdecl*)(class v8::FunctionCallbackInfo<class v8::Value> const &),class v8::Local<class v8::Value>,class v8::Local<class v8::Signature>,int,enum v8::ConstructorBehavior,enum v8::SideEffectType,class v8::CFunction const *)" (__imp_?New@FunctionTemplate@v8@@SA?AV?$Local@VFunctionTemplate@v8@@@2@PEAVIsolate@2@P6AXAEBV?$FunctionCallbackInfo@VValue@v8@@@2@@ZV?$Local@VValue@v8@@@2@V?$Local@VSignature@v8@@@2@HW4ConstructorBehavior@2@W4SideEffectType@2@PEBVCFunction@2@@Z) [D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\bindings.vcxproj]
    已定义且可能匹配的符号上的提示:
      "__declspec(dllimport) public: static class v8::Local<class v8::Array> __cdecl v8::Array::New(class v8::Isolate *,int)" (__imp_?New@Array@v8@@SA?AV?$Local@VArray@v8@@@2@PEAVIsolate@2@H@Z)
      "__declspec(dllimport) public: static class v8::Local<class v8::Boolean> __cdecl v8::Boolean::New(class v8::Isolate *,bool)" (__imp_?New@Boolean@v8@@SA?AV?$Local@VBoolean@v8@@@2@PEAVIsolate@2@_N@Z)
      "__declspec(dllimport) public: static class v8::Local<class v8::External> __cdecl v8::External::New(class v8::Isolate *,void *)" (__imp_?New@External@v8@@SA?AV?$Local@VExternal@v8@@@2@PEAVIsolate@2@PEAX@Z)
      "__declspec(dllimport) public: static class v8::Local<class v8::Integer> __cdecl v8::Integer::New(class v8::Isolate *,int)" (__imp_?New@Integer@v8@@SA?AV?$Local@VInteger@v8@@@2@PEAVIsolate@2@H@Z)
      "__declspec(dllimport) public: static class v8::Local<class v8::Object> __cdecl v8::Object::New(class v8::Isolate *)" (__imp_?New@Object@v8@@SA?AV?$Local@VObject@v8@@@2@PEAVIsolate@2@@Z)
      "__declspec(dllimport) public: static class v8::Local<class v8::ObjectTemplate> __cdecl v8::ObjectTemplate::New(class v8::Isolate *,class v8::Local<class v8::FunctionTemplate>)" (__imp_?New@ObjectTemplate@v8@@SA?AV?$Local@VObjectTemplate@v8@@@2@PEAVIsolate@2@V?$Local@VFunctionTemplate@v8@@@2@@Z)
D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\Release\bindings.node : fatal error LNK1120: 1 个无法解析的外部命令 [D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Dev\electron-quick-start\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Dev\\electron-quick-start\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=9.0.3" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd D:\Dev\electron-quick-start\node_modules\@serialport\bindings
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.16.3 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\Li\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2019 (16.5.30104.148) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\Li\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'D:\\Dev\\electron-quick-start\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Dev\\electron-quick-start\\node_modules\\@serialport\\bindings\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Dev\\electron-quick-start\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Li\\.electron-gyp\\9.0.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Li\\.electron-gyp\\9.0.3',
gyp info spawn args   '-Dnode_gyp_dir=D:\\Dev\\electron-quick-start\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Li\\\\.electron-gyp\\\\9.0.3\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Dev\\electron-quick-start\\node_modules\\@serialport\\bindings',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Dev\\electron-quick-start\\node_modules\\@serialport\\bindings\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
  serialport.cpp
  serialport_win.cpp
  win_delay_load_hook.cc
C:\Users\Li\.electron-gyp\9.0.3\include\node\v8.h(9116,39): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version. (编译源文件 ..\src\serialport_win.cpp) [D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\bindings.vcxproj]
C:\Users\Li\.electron-gyp\9.0.3\include\node\v8.h(9124,42): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version. (编译源文件 ..\src\serialport_win.cpp) [D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\bindings.vcxproj]
C:\Users\Li\.electron-gyp\9.0.3\include\node\v8.h(9116,39): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version. (编译源文件 ..\src\serialport.cpp) [D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\bindings.vcxproj]
C:\Users\Li\.electron-gyp\9.0.3\include\node\v8.h(9124,42): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version. (编译源文件 ..\src\serialport.cpp) [D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\bindings.vcxproj]
    正在创建库 D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\Release\bindings.lib 和对象 D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\Release\bindings.exp
serialport.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: static class v8::Local<class v8::FunctionTemplate> __cdecl v8::FunctionTemplate::New(class v8::Isolate *,void (__cdecl*)(class v8::FunctionCallbackInfo<class v8::Value> const &),class v8::Local<class v8::Value>,class v8::Local<class v8::Signature>,int,enum v8::ConstructorBehavior,enum v8::SideEffectType,class v8::CFunction const *)" (__imp_?New@FunctionTemplate@v8@@SA?AV?$Local@VFunctionTemplate@v8@@@2@PEAVIsolate@2@P6AXAEBV?$FunctionCallbackInfo@VValue@v8@@@2@@ZV?$Local@VValue@v8@@@2@V?$Local@VSignature@v8@@@2@HW4ConstructorBehavior@2@W4SideEffectType@2@PEBVCFunction@2@@Z) [D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\bindings.vcxproj]
    已定义且可能匹配的符号上的提示:
      "__declspec(dllimport) public: static class v8::Local<class v8::Array> __cdecl v8::Array::New(class v8::Isolate *,int)" (__imp_?New@Array@v8@@SA?AV?$Local@VArray@v8@@@2@PEAVIsolate@2@H@Z)
      "__declspec(dllimport) public: static class v8::Local<class v8::Boolean> __cdecl v8::Boolean::New(class v8::Isolate *,bool)" (__imp_?New@Boolean@v8@@SA?AV?$Local@VBoolean@v8@@@2@PEAVIsolate@2@_N@Z)
      "__declspec(dllimport) public: static class v8::Local<class v8::External> __cdecl v8::External::New(class v8::Isolate *,void *)" (__imp_?New@External@v8@@SA?AV?$Local@VExternal@v8@@@2@PEAVIsolate@2@PEAX@Z)
      "__declspec(dllimport) public: static class v8::Local<class v8::Integer> __cdecl v8::Integer::New(class v8::Isolate *,int)" (__imp_?New@Integer@v8@@SA?AV?$Local@VInteger@v8@@@2@PEAVIsolate@2@H@Z)
      "__declspec(dllimport) public: static class v8::Local<class v8::Object> __cdecl v8::Object::New(class v8::Isolate *)" (__imp_?New@Object@v8@@SA?AV?$Local@VObject@v8@@@2@PEAVIsolate@2@@Z)
      "__declspec(dllimport) public: static class v8::Local<class v8::ObjectTemplate> __cdecl v8::ObjectTemplate::New(class v8::Isolate *,class v8::Local<class v8::FunctionTemplate>)" (__imp_?New@ObjectTemplate@v8@@SA?AV?$Local@VObjectTemplate@v8@@@2@PEAVIsolate@2@V?$Local@VFunctionTemplate@v8@@@2@@Z)
D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\Release\bindings.node : fatal error LNK1120: 1 个无法解析的外部命令 [D:\Dev\electron-quick-start\node_modules\@serialport\bindings\build\bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Dev\electron-quick-start\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Dev\\electron-quick-start\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=9.0.3" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd D:\Dev\electron-quick-start\node_modules\@serialport\bindings
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (D:\Dev\electron-quick-start\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (D:\Dev\electron-quick-start\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.error (D:\Dev\electron-quick-start\node_modules\rxjs\internal\Subscriber.js:156:26)
    at Subscriber._error (D:\Dev\electron-quick-start\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (D:\Dev\electron-quick-start\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (D:\Dev\electron-quick-start\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (D:\Dev\electron-quick-start\node_modules\rxjs\internal\Subscriber.js:72:18)
    at SafeSubscriber._next (D:\Dev\electron-quick-start\node_modules\spawn-rx\lib\src\index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (D:\Dev\electron-quick-start\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (D:\Dev\electron-quick-start\node_modules\rxjs\internal\Subscriber.js:143:22)
```

### Code to Reproduce the Issue

```
.\node_modules\.bin\electron-rebuild.cmd
```

### Versions, Operating System and Hardware

- SerialPort@9.0.0
- Node.js v12.16.3
- Windows 10
- node-gyp v6.1.0
- VS2019

**Comment by KernelErr** [comment]
Fixed. Seems that it caused by my corrupted `node.lib` file. Delelte it can solve this problem.
