### ISSUE TITLE
install error (win10)

### ISSUE THREAD

**Issue by oase473** [serialport/node-serialport#2178]
### Summary of Problem

- What are you trying to do?
Install serialport on Windows 10

- What happens?
Some errors incl. fatal error LNK1106

- What should have happened?
Successful install of serialport

### Code to Reproduce the Issue

```js
npm i serialport
> @serialport/bindings@9.0.2 install C:\Users\pybt07\Developer\github\modbus-serial\node_modules\@serialport\bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install unable to verify the first certificate

C:\Users\pybt07\Developer\github\modbus-serial\node_modules\@serialport\bindings>if not defined npm_config_node_gyp (node "C:\Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den 
  serialport.cpp
  serialport_win.cpp
  win_delay_load_hook.cc
C:\\Users\\pybt07\\AppData\\Local\\node-gyp\\Cache\\14.15.0\\x64\\node.lib : fatal error LNK1106: Ung³ltige Datei oder Datentr
\build\bindings.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed wit
gyp ERR! stack     at ChildProcess.onExit (C:\Users\pybt07\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\buil
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pybt07\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modu
gyp ERR! cwd C:\Users\pybt07\Developer\github\modbus-serial\node_modules\@serialport\bindings
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN modbus-serial@1.0.0 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@9.0.2 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @serialport/bindings@9.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pybt07\AppData\Roaming\npm-cache\_logs\2020-11-23T13_48_19_713Z-debug.log

// Code
```

### Versions, Operating System and Hardware

- SerialPort@?

- Node.js v?
v14.15.0

- npm v 
6.14.9

- Windows? Linux? Mac?
Windows_NT 10.0.18363
(Windows 10?)

- Hardware and chipset? (Prolific/FTDI/Other)
Core i5 8th vPro Generation

**Comment by GazHank** [comment]
I believe this is the same problem as https://github.com/serialport/node-serialport/issues/2176 and has now been resolved
