### ISSUE TITLE
NODE_MODULE_VERSION issue

### ISSUE THREAD

**Issue by Sam-Dvorack** [serialport/node-serialport#2211]
I am facing the below error

App threw an error during load
Error: The module '\\?\D:\WAS_2.0\Electron\electron-test\node_modules\@serialport\bindings\build\Release\bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 76. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)

I tried rebuilding it doesn't seem to work,
    
Versions:
serialport v9.0.6
Node v12.16.3
NPM v6.14.7
Electron v8.2.1

**Comment by ngvcanh** [comment]
Normally with this issue, I to do the follow task it will work (electron <= `11.1.1`):

- Delete `node_modules` folder
- Delete `package-lock.json`
- Run follows command:

```
npm i
npm install electron-rebuild --save-dev

# For Linux
./node_modules/.bin/electron-rebuild

# For Windows
.\node_modules\.bin\electron-rebuild
```

But today I make new project and install electron with version `11.2.2`, it not work and error node module:

```
NODE_MODULE_VERSION 85. This version of Node.js requires
NODE_MODULE_VERSION 82. Please try re-compiling or re-installing
```
