### ISSUE TITLE
Help needed with with installation. thanx

### ISSUE THREAD

**Issue by djalexnl** [serialport/node-serialport#2308]
I wanted to install this node on my Rasparian Pi 4 with HASSIO and Nodered. 

The following error occured... im kinda newbie with this but definately does not look good.

hassio version core-2021.8.6 latest Node Red. etc. 

Maybe some of you can help this newby on the good path..

`-----------------------------------------------------------
2021-08-11T12:05:37.459Z Install : node-red-contrib-rfxcom 2.11.3

2021-08-11T12:05:37.180Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-rfxcom@2.11.3
2021-08-11T12:05:50.016Z [err] npm
2021-08-11T12:05:50.017Z [err]  
2021-08-11T12:05:50.018Z [err] ERR!
2021-08-11T12:05:50.018Z [err]  
2021-08-11T12:05:50.019Z [err] code
2021-08-11T12:05:50.019Z [err]  1
2021-08-11T12:05:50.021Z [err] npm
2021-08-11T12:05:50.021Z [err]  
2021-08-11T12:05:50.022Z [err] ERR!
2021-08-11T12:05:50.022Z [err]  
2021-08-11T12:05:50.022Z [err] path
2021-08-11T12:05:50.023Z [err]  /config/node-red/node_modules/@serialport/bindings
2021-08-11T12:05:50.036Z [err] npm
2021-08-11T12:05:50.036Z [err]  
2021-08-11T12:05:50.037Z [err] ERR!
2021-08-11T12:05:50.037Z [err]  command failed
2021-08-11T12:05:50.038Z [err] npm
2021-08-11T12:05:50.038Z [err]  
2021-08-11T12:05:50.038Z [err] ERR!
2021-08-11T12:05:50.038Z [err]  
2021-08-11T12:05:50.039Z [err] command
2021-08-11T12:05:50.039Z [err]  sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2021-08-11T12:05:50.039Z [err] npm
2021-08-11T12:05:50.040Z [err]  
2021-08-11T12:05:50.040Z [err] ERR!
2021-08-11T12:05:50.040Z [err]  prebuild-install WARN install No prebuilt binaries found (target=14.17.1 runtime=node arch=arm64 libc=musl platform=linux)
2021-08-11T12:05:50.041Z [err] npm
2021-08-11T12:05:50.041Z [err]  
2021-08-11T12:05:50.041Z [err] ERR!
2021-08-11T12:05:50.041Z [err]  gyp info it worked if it ends with ok
2021-08-11T12:05:50.042Z [err] npm
2021-08-11T12:05:50.042Z [err]  
2021-08-11T12:05:50.042Z [err] ERR!
2021-08-11T12:05:50.042Z [err]  gyp info using node-gyp@7.1.2
2021-08-11T12:05:50.043Z [err] npm
2021-08-11T12:05:50.043Z [err]  
2021-08-11T12:05:50.043Z [err] ERR!
2021-08-11T12:05:50.044Z [err]  gyp info using node@14.17.1 | linux | arm64
2021-08-11T12:05:50.044Z [err] npm
2021-08-11T12:05:50.044Z [err]  
2021-08-11T12:05:50.044Z [err] ERR!
2021-08-11T12:05:50.045Z [err]  gyp info find Python using Python version 3.9.5 found at "/usr/bin/python3"
2021-08-11T12:05:50.045Z [err] npm
2021-08-11T12:05:50.045Z [err]  
2021-08-11T12:05:50.045Z [err] ERR!
2021-08-11T12:05:50.046Z [err]  gyp info spawn /usr/bin/python3
2021-08-11T12:05:50.046Z [err] npm
2021-08-11T12:05:50.046Z [err]  
2021-08-11T12:05:50.046Z [err] ERR!
2021-08-11T12:05:50.047Z [err]  gyp info spawn args [
2021-08-11T12:05:50.047Z [err] npm
2021-08-11T12:05:50.047Z [err]  
2021-08-11T12:05:50.047Z [err] ERR!
2021-08-11T12:05:50.048Z [err]  gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2021-08-11T12:05:50.048Z [err] npm
2021-08-11T12:05:50.048Z [err]  
2021-08-11T12:05:50.048Z [err] ERR!
2021-08-11T12:05:50.051Z [err]  gyp info spawn args   'binding.gyp',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   '-f',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   'make',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   '-I',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   '/config/node-red/node_modules/@serialport/bindings/build/config.gypi',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   '-I',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   '-I',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   '/root/.cache/node-gyp/14.17.1/include/node/common.gypi',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   '-Dvisibility=default',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.17.1',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.17.1/<(target_arch)/node.lib',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   '-Dmodule_root_dir=/config/node-red/node_modules/@serialport/bindings',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   '-Dnode_engine=v8',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   '--depth=.',
2021-08-11T12:05:50.051Z [err] npm
2021-08-11T12:05:50.051Z [err]  ERR! gyp info spawn args   '--no-parallel',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   '--generator-output',
2021-08-11T12:05:50.051Z [err] npm ERR! gyp info spawn args   'build',
2021-08-11T12:05:50.051Z [err] npm
2021-08-11T12:05:50.051Z [err]  ERR! gyp info spawn args   '-Goutput_dir=.'
2021-08-11T12:05:50.051Z [err] npm ERR!
2021-08-11T12:05:50.051Z [err]  gyp info spawn args ]
2021-08-11T12:05:50.051Z [err] npm ERR! gyp ERR! build error 
2021-08-11T12:05:50.052Z [err] npm ERR! gyp ERR! stack Error: not found: make
2021-08-11T12:05:50.052Z [err] npm 
2021-08-11T12:05:50.052Z [err] ERR! gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:10:17)
2021-08-11T12:05:50.052Z [err] npm ERR!
2021-08-11T12:05:50.052Z [err]  gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:18
2021-08-11T12:05:50.052Z [err] npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
2021-08-11T12:05:50.052Z [err] npm
2021-08-11T12:05:50.052Z [err]  ERR! gyp ERR! stack     at step (/usr/lib/node_modules/npm/node_modules/which/which.js:54:21)
2021-08-11T12:05:50.052Z [err] npm 
2021-08-11T12:05:50.052Z [err] ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:71:22
2021-08-11T12:05:50.052Z [err] npm ERR!
2021-08-11T12:05:50.052Z [err]  gyp ERR! stack     at new Promise (<anonymous>)
2021-08-11T12:05:50.052Z [err] npm ERR! gyp ERR! stack     at subStep (/usr/lib/node_modules/npm/node_modules/which/which.js:69:33)
2021-08-11T12:05:50.052Z [err] npm
2021-08-11T12:05:50.053Z [err]  ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:80:22
2021-08-11T12:05:50.053Z [err] npm 
2021-08-11T12:05:50.053Z [err] ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2021-08-11T12:05:50.053Z [err] npm ERR! gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2021-08-11T12:05:50.053Z [err] npm ERR! gyp ERR! System Linux 5.10.17-v8
2021-08-11T12:05:50.053Z [err] npm
2021-08-11T12:05:50.053Z [err]  ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-08-11T12:05:50.053Z [err] npm ERR!
2021-08-11T12:05:50.053Z [err]  gyp ERR! cwd /config/node-red/node_modules/@serialport/bindings
2021-08-11T12:05:50.053Z [err] npm ERR!
2021-08-11T12:05:50.053Z [err]  gyp ERR! node -v v14.17.1
2021-08-11T12:05:50.053Z [err] npm ERR! gyp ERR! node-gyp -v v7.1.2
2021-08-11T12:05:50.054Z [err] npm ERR! gyp ERR! not ok
2021-08-11T12:05:50.176Z [err] 
2021-08-11T12:05:50.176Z [err] npm ERR! A complete log of this run can be found in:
2021-08-11T12:05:50.176Z [err] npm ERR!     /root/.npm/_logs/2021-08-11T12_05_50_060Z-debug.log
2021-08-11T12:05:50.212Z rc=1`

**Comment by GazHank** [comment]
hi @djalexnl

based on the environment info you have shared it looks like the prebuilds wont work for you so you will need to have the build tools installed and configured for your environment.  There are instructions for installing on Raspberry-pi at https://serialport.io/docs/guide-installation#raspberry-pi-linux

If there are any steps in the instructions which are unclear or could be improved then do please let us know
